name: Tests
on:
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: DeLaGuardo/setup-clojure@05cb4bfdf57855f122e75b71e45224775cdfc4a0 # 9.5
        with:
          clj-kondo: '2022.10.14'
          bb: 1.0.164

      - name: clj-kondo
        run: |
          clj-kondo --lint src --config '{:output {:pattern "::{{level}} file={{filename}},line={{row}},col={{col}}::{{message}}"}}'

      - name: Unit Tests
        run: make test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Dry Run
        run: make dryrun
        id: integration-tests
        env:
          INPUT_BUMP_VERSION_SCHEME: minor
          INPUT_MAX_COMMITS: 5
          INPUT_TAG_PREFIX: v
          INPUT_RELEASE_NAME: <RELEASE_TAG>
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Output Parameters
        run: |
          echo "Got tag version ${{ steps.integration-tests.outputs.tag_name }}"
          echo "Got version ${{ steps.integration-tests.outputs.version }}"
          echo "Got body ${{ steps.integration-tests.outputs.body }}"

      - name: Container Builds
        run: docker build . -t step-security/release-on-push-action

      - name: Container Test
        run: docker run -e INPUT_BUMP_VERSION_SCHEME -e INPUT_MAX_COMMITS -e INPUT_TAG_PREFIX -e INPUT_RELEASE_NAME -e GITHUB_API_URL -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_TOKEN step-security/release-on-push-action --dry-run
        env:
          INPUT_BUMP_VERSION_SCHEME: minor
          INPUT_MAX_COMMITS: 5
          INPUT_TAG_PREFIX: v
          INPUT_RELEASE_NAME: <RELEASE_TAG>
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
